---
  - name: "Run ETH node and setup Nginx"
    hosts: localhost
    connection: local 
    become: yes
    become_method: sudo
    vars:
       external_rpc_port: 80
       external_ip: localhost
       ethnode_persistant_storage: /data/etherium
       goeth_docker_image: ethereum/client-go
       container_name: ETH_node

    tasks:
    - name: Creates directory for persistant store eth
      file:
        path: "{{ ethnode_persistant_storage }}"
        state: directory

    - name: Run eth docker image
      docker_container:
        name: "{{ container_name }}"
        recreate: yes
        image: "{{ goeth_docker_image }}"
        command: --http --http.corsdomain * --http.port 8545 --http.addr 0.0.0.0
        ports:
         - "30303:30303"
         - "8545:8545"
        volumes:
         - "{{ ethnode_persistant_storage }}:/root"

    - name: "apt-get update"
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: "install nginx"
      apt:
        name: ['nginx']
        state: latest

    - name: delete default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent
      notify: restart nginx

    - name: copy nginx reversproxy.conf
      template:
        src: reversproxy.conf.j2
        dest: /etc/nginx/sites-enabled/{{ external_ip }}
        owner: root
        group: root
        mode: '0644'
      notify: restart nginx

    - name: Check container started
      wait_for:
        host: "127.0.0.1"
        port: 8545

    - name: Force handler run
      meta: flush_handlers

    - name: Check container port
      ansible.builtin.uri:
        url: http://127.0.0.1:8545
        method: POST
        body: "{'jsonrpc':'2.0','method':'net_version','params':[],'id':67}"
        status_code: 200
        body_format: json

    - name: Check Nginx port
      ansible.builtin.uri:
        url: http://{{ external_ip }}:{{ external_rpc_port }}
        method: POST
        body: "{'jsonrpc':'2.0','method':'net_version','params':[],'id':67}"
        status_code: 200
        body_format: json

    handlers:
      - name: restart nginx
        service:
          name: nginx
          state: restarted
